services:
  - type: worker
    name: JavoAgeBot
    runtime: python
    repo: https://github.com/javohir-dls/Javoagebot
    branch: main
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
